### ISSUE TITLE
1.19.2 - Failed to Start after Updating to ZeroCore2-1.19.2-2.1.31.jar from  ZeroCore2-1.19.2-2.1.30.jar

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ZeroNoRyouki/ZeroCore#1]
Crash Log https://gist.github.com/P3rf3ctXZer0/c282f58903a1bf1623dc1a4aa148ae13

**Comment by ZeroNoRyouki** [comment]
Wrong repository but I get It. Follow it here: https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/110
